### ISSUE TITLE
Antd Select component onMouseDown events should not propagate (or should be configurable)

### ISSUE THREAD

**Issue by matt-koevort** [xrutayisire/react-js-cron#51]
**Describe the bug**
Rendering this component inside another that has a MouseEvent handler causes that handler to fire when the antd `Select` component's dropdown items are clicked. For ancestors like modals, this causes the modal to close as most modals would have MouseEvent handlers for closing on click outside (see [codesandbox](https://codesandbox.io/s/nervous-james-uprzgq?file=/src/App.js)).

I have created two separate PRs to address this.
1. https://github.com/xrutayisire/react-js-cron/pull/49 - provides full control to the user to specify select props for all field types
2. https://github.com/xrutayisire/react-js-cron/pull/50 - simply ensures that `onMouseDown` on antd Select components does not propagate the event

**To Reproduce**
1. Use `Cron` component inside a Modal (our issue is with Sanity modal component)
2. Select an element from any dropdown/select in the Cron component
3. The modal will close

**Expected behavior**
Clicking an item in a Select dropdown should not close the modal.

**Screenshots**

**CodeSandbox**
https://codesandbox.io/s/nervous-james-uprzgq?file=/src/App.js

**Versions (please complete the following information):**
 - react-js-cron version 3.0.1
 - Ant Design version: 5.2.3
 - React version: 18.2.0
 - OS: -
 - Browser chrome

**Additional context**

**Comment by xrutayisire** [comment]
Hi,

Thank you for the bug report. If you can check up the MRs pipelines and I can release a new version after this!

Thanks a lot!

**Comment by xrutayisire** [comment]
No activity since Mars and now master changed. If you still need the feature, please update the PRs. Ensure everything is fine and create new PRs. Thanks for the contribution!

**Comment by vpfaiz** [comment]
This is still an issue. I am trying to use this with ShadCN AlertDialog and the clicks don't register.

**Comment by xrutayisire** [comment]
Sorry, I don't have time for this PR. 
You can take the code, update it following the recommendations and I would approve it 🙂

**Comment by ligoo** [comment]
```css
.ant-select-dropdown {
    position: fixed !important;
    z-index: 1000 !important;
    pointer-events: all !important;
}

.ant-select-item {
    pointer-events: all !important;
}

.ant-select-item-option {
    pointer-events: all !important;
    user-select: none;
}

.ant-select-item-option-content {
    pointer-events: all !important;
}

.react-js-cron .ant-select-dropdown {
    pointer-events: all !important;
}

.react-js-cron-select {
    z-index: 100;
}
```
fixed it for me.
